# Generated by Django 4.2.25 on 2025-10-30 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clint',
            name='idC',
        ),
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='idC',
        ),
        migrations.RemoveField(
            model_name='order',
            name='idO',
        ),
        migrations.RemoveField(
            model_name='order',
            name='idP',
        ),
        migrations.RemoveField(
            model_name='prodect',
            name='idP',
        ),
        migrations.AddField(
            model_name='order',
            name='clint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='makeup.clint'),
        ),
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeup.order')),
                ('prodect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeup.prodect')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='prodects',
            field=models.ManyToManyField(through='makeup.OrderedProduct', to='makeup.prodect'),
        ),
    ]
