# Generated by Django 4.2.25 on 2025-11-06 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0002_remove_clint_idc_remove_order_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prodect',
            old_name='img',
            new_name='image',
        ),
    ]
